---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: loki331/chandu:dbimage
   ports:
     - "3306:3306"

 application:
   image: loki331/chandu:appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
